import {BONUS_TYPES} from "./bonus-types";
import {CUBES_MAP} from "./func-types";

export const PRESETS: CUBES_MAP[] = [
    [{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},],
    [{genValue: 2, bonus: null},{genValue: 2, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 2, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 2, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 2, bonus: null},{genValue: 1, bonus: null},],
    [{genValue: 3, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 3, bonus: null},{genValue: 3, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 3, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 3, bonus: null},{genValue: 3, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},],
    [{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},],
    [{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 1, bonus: null},],
    [{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 3, bonus: null},{genValue: 0, bonus: null},{genValue: 3, bonus: null},{genValue: 3, bonus: null},{genValue: 0, bonus: null},{genValue: 3, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},],
    [{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},],
    [{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 2, bonus: null},],
    [{genValue: 3, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 3, bonus: null},{genValue: 2, bonus: null},{genValue: 2, bonus: null},{genValue: 3, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 3, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},],
    [{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},{genValue: 0, bonus: null},{genValue: 1, bonus: null},],
    [{genValue: 1, bonus: null},{genValue: 2, bonus: null},{genValue: 2, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 0, bonus: null},{genValue: 2, bonus: null},{genValue: 2, bonus: null},{genValue: 1, bonus: null},],
    [{genValue: 1, bonus: null},{genValue: 3, bonus: null},{genValue: 0, bonus: null},{genValue: 3, bonus: null},{genValue: 2, bonus: null},{genValue: 2, bonus: null},{genValue: 3, bonus: null},{genValue: 0, bonus: null},{genValue: 3, bonus: null},{genValue: 1, bonus: null},],

];