export enum SESSION_STATE {
    AWAITING_OPPONENT,
    AWAITING_CONFIRMATION,
    READY,
    GAME_IN_PROGRESS,
    GAME_PAUSED,
    GAME_OVER,
    DISPOSE_ROOM_IDLE,
    DISPOSE_ROOM_UNREADY,
    DISPOSE_ROOM_PLAYER_DISCONNECTED,
    PLAYER_DISCONNECTED,
    STANDBY
}
